# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v4.6.0'
    hooks:
      - id: 'check-executables-have-shebangs'
      - id: 'check-merge-conflict'
      - id: 'no-commit-to-branch'
        args: ['--branch', 'devel', '--branch', 'master']
      - id: 'check-ast'
      - id: 'check-json'
      - id: 'check-yaml'
      - id: 'end-of-file-fixer'
      - id: 'trailing-whitespace'
        args: ['--markdown-linebreak-ext=md']
        exclude: '.gitlab/issue_templates/bugreport.md'
  - repo: 'https://github.com/crate-ci/typos'
    rev: 'v1.36.2'
    hooks:
      - id: 'typos'
        args: ['-c', 'utils/.typos.toml']
        exclude: |-
          (?x)
            ^.clang-tidy$|
            ^config/|
            ^cmake/example/t.c$|
            ^tests/
  - repo: 'https://github.com/pocc/pre-commit-hooks.git'
    rev: 'v1.3.5'
    hooks:
      - id: 'clang-tidy'
        # Mute linker warning on unused flags "-Wl,-rpath=<mpc-install>/lib64"
        args: ['--extra-arg=-Wnounused-command-line-argument', '--quiet', '--use-color']
        exclude: |-
          (?x)
            ^cmake/example/t.c$|
            ^tests/
          # FIXME:
          # 1. sctk_lib_thread_db.c contains unmuteable false positives on "ambiguous" calls
          #     with  # pragma weak and extern functions. This a known LLVM issue, see
          #    https://github.com/llvm/llvm-project/issues/16067
          # 2. dataloop and mpitypes contain files from an external library
          #    adapted to MPC. Within those files, there are a number of errors
          #    and warning that would probably require a large refactoring.
      - id: 'uncrustify'
        args: ['-c', 'uncrustify.cfg', '-q']
        exclude: |-
          (?x)
            ^src/MPC_Lowcomm/src/cplane/auth|
            ^src/MPC_Common/src/debugger.c$|
            ^src/MPC_OpenMP/src/mpcomp_alloc\.c$|
            ^cmake/example/t.c$|
            ^tests/
  - repo: 'local'
    hooks:
      - id: 'git-blame-ignore-revs'
        name: 'configure git blame to ignore reformatting commits'
        description: 'Configure git blame to ignore commits listed in .git-blame-ignore-revs'
        entry: 'git config blame.ignoreRevsFile .git-blame-ignore-revs'
        language: 'system'
        pass_filenames: false
        minimum_pre_commit_version: '0'
exclude: |-
  (?x)
    uthash\.h$|
    utlist\.h$|
    utarray\.h$|
    ^src/MPC_Common/include/sctk_no_alloc\.h$|
    ^src/MPC_Common/include/mpc_common_profiler_keys\.h$|
    ^src/MPC_Fortran|
    ^src/MPC_IO/src/romio|
    ^src/MPC_Lowcomm/src/portals|
    modex|
    ^src/MPC_MPI/src/dataloop|
    ^src/MPC_MPI/src/mpitypes|
    ^src/MPC_MPI/include/nbc\.h$|
    ^src/MPC_MPI/src/mpc_nbc\.c$|
    ^src/MPC_OpenMP/include/omp_lib\.h$|
    ^src/MPC_OpenMP/include/omp_lib_kinds\.h$|
    ^src/MPC_OpenMP/tools/|
    ^src/MPC_Tests|
    ^src/MPC_Thread_db/src/gdb/linux-thread-db\.c$|
    ^src/MPC_Thread_db/src/sctk_lib_thread_db\.c$|
    ^src/MPC_Thread_db/src/test/|
    hwloc|
    \.(m4|3in|f90)$
