[default.extend-words]
anc = "anc"
aout = "aout"
aranges = "aranges"
ba = "ba"
floatint = "floatint"
improbe = "improbe"
nin = "nin"
nd = "nd"
parms = "parms"
pn = "pn"
rela = "rela"
ser = "ser"
scond = "scond"
thr = "thr"
tru = "tru"
typ = "typ"
wrk = "wrk"
wronly = "wronly"

[type.S]
extend-glob = ["*.S"]
check-file = false

[type.bib]
extend-glob = ["*.bib"]
check-file = false

[files]
extend-exclude = ["src/MPC_Lowcomm/src/portals*/*", "src/MPC_IO/src/romio/*", "src/MPC_Tests/*", "config/*"]
